### ISSUE TITLE
Crash when cancelling DocV flow

### ISSUE THREAD

**Issue by jolurz** [socure-inc/socure-docv-sdk-android#27]
Steps to replicate:

1. Launch document verification flow.
2. Click on "Consent" to proceed to scan front of ID.
3. Click on the "X" icon to cancel the flow.
4. Re-launch document verification flow.

Please note that this only happens after cancelling the flow and sometimes the app crashes even without the 4th step. Could it be a retained object triggering this action even after the flow got cancelled?

```

FATAL EXCEPTION: main
                 Process: com.activehours.debug, PID: 30266
                 java.lang.NoSuchMethodError: No static method setPlatformTextInputServiceInterceptor(Lkotlin/jvm/functions/Function1;)V in class Landroidx/compose/ui/platform/AndroidComposeView_androidKt; or its super classes (declaration of 'androidx.compose.ui.platform.AndroidComposeView_androidKt' appears in /data/app/~~COQ_Sn5QHQR2J99iU6lkKw==/com.activehours.debug-936-VjAWLkQJvc5Gevl_XQ==/base.apk)
                 	at com.socure.idplus.device.internal.input.manager.compose.d.a(SourceFile:7)
                 	at com.socure.idplus.device.internal.input.manager.compose.d.a(SourceFile:3)
                 	at com.socure.idplus.device.internal.input.manager.a.a(SourceFile:4)
                 	at com.socure.idplus.device.internal.input.manager.a.a(SourceFile:5)
                 	at com.socure.idplus.device.internal.input.manager.a.a(SourceFile:4)
                 	at com.socure.idplus.device.internal.input.manager.a.a(SourceFile:5)
                 	at com.socure.idplus.device.internal.input.manager.a.a(SourceFile:4)
                 	at com.socure.idplus.device.internal.input.manager.a.a(SourceFile:5)
                 	at com.socure.idplus.device.internal.input.manager.a.a(SourceFile:2)
                 	at com.socure.idplus.device.internal.behavior.manager.g.a(SourceFile:14)
                 	at com.socure.idplus.device.internal.behavior.manager.g.<init>(Unknown Source:88)
                 	at com.socure.idplus.device.internal.n.invoke(SourceFile:10)
                 	at com.socure.idplus.device.internal.sigmaDeviceSession.manager.a.invoke(SourceFile:7)
                 	at com.socure.idplus.device.internal.sigmaDeviceSession.manager.c.invoke(SourceFile:3)
                 	at com.socure.idplus.device.internal.network.b.onResponse(SourceFile:0)
                 	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
                 	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7872)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by rburunkayaSocure** [comment]
Hi @jolurz 

Could you please confirm the ComposeView version you are using? It seems the issue may be related to your current ComposeView version. On Android platform, Socure SDKs require `ComposeView` version `1.6.3` or higher to function correctly.

Thanks,

**Comment by jolurz** [comment]
Hello @rburunkayaSocure, thanks for the information. It seems like we are using androidx.compose.ui:ui:1.4.3. Is there any documentation that describes this kind of requirements for the SDK?

**Comment by rburunkayaSocure** [comment]
Hey @jolurz 

You can this information is available on the DevHub under Digital Intelligence SDKs migration guideline section.

Thanks,
