### ISSUE TITLE
Crash in release build

### ISSUE THREAD

**Issue by edenman** [socure-inc/socure-docv-sdk-android#28]
```
12-10 15:19:22.237 E/AndroidRuntime(27505): FATAL EXCEPTION: DefaultDispatcher-worker-40
12-10 15:19:22.237 E/AndroidRuntime(27505): Process: com.x.android, PID: 27505
12-10 15:19:22.237 E/AndroidRuntime(27505): java.lang.UnsatisfiedLinkError: Can't obtain peer field ID for class com.sun.jna.Pointer
12-10 15:19:22.237 E/AndroidRuntime(27505):     at com.sun.jna.Native.initIDs(Native Method)
12-10 15:19:22.237 E/AndroidRuntime(27505):     at com.sun.jna.Native.<clinit>(Unknown Source:585)
12-10 15:19:22.237 E/AndroidRuntime(27505):     at com.google.android.gms.internal.mlkit_vision_barcode.wb.B(Unknown Source:84)
12-10 15:19:22.237 E/AndroidRuntime(27505):     at com.app.l9.a(Unknown Source:197)
12-10 15:19:22.237 E/AndroidRuntime(27505):     at com.app.d4.a(Unknown Source:294)
12-10 15:19:22.237 E/AndroidRuntime(27505):     at com.app.a4.invokeSuspend(Unknown Source:16)
12-10 15:19:22.237 E/AndroidRuntime(27505):     at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:8)
12-10 15:19:22.237 E/AndroidRuntime(27505):     at kotlinx.coroutines.r0.run(Unknown Source:106)
12-10 15:19:22.237 E/AndroidRuntime(27505):     at kotlinx.coroutines.scheduling.b.run(Unknown Source:115)
12-10 15:19:22.237 E/AndroidRuntime(27505):     Suppressed: kotlinx.coroutines.internal.f: [g2{Cancelling}@e68fd63, Dispatchers.Default]
```
We have isMinifyEnabled=true and the recommended line in our proguard rules: `-keep class com.socure.idplus.** { *; }`

docv-capture version 4.3.2
socure-devicerisk version 4.3.1

Any advice?

**Comment by edenman** [comment]
I tried adding this to our proguard rules

**Comment by rburunkayaSocure** [comment]
Hi @edenman 

Thanks for contacting us. We are going to review the issue and get back to you soon.

Thanks,

**Comment by rburunkayaSocure** [comment]
Hi @edenman 

Could you please add the following two rules to your ProGuard configuration and let us know if this resolves the issue?
```
-keep class com.sun.jna.** { *; } 
-keep class com.google.android.gms.internal.mlkit_vision_barcode.** { *; }
```
Additionally, are you using the JNA library? If so, could you please share the version you're currently using?

Thanks.

**Comment by edenman** [comment]
Sorry, this was a false alarm, not related to this SDK. The stacktrace was misleading 😭  Here's the actual issue

https://github.com/ionspin/kotlin-multiplatform-libsodium/discussions/39
